import { Comments } from './interfaces/comments';

export const COMMENTS: Comments[] = [
  {
    kind: 't1',
    data: {
      total_awards_received: 0,
      approved_at_utc: null,
      comment_type: null,
      awarders: [],
      mod_reason_by: null,
      banned_by: null,
      author_flair_type: 'text',
      removal_reason: null,
      link_id: 't3_lbx5js',
      author_flair_template_id: '40bbb600-4ff1-11e7-bf1a-0e2aff1d0230',
      likes: null,
      replies: '',
      user_reports: [],
      saved: false,
      id: 'glwllvw',
      banned_at_utc: null,
      mod_reason_title: null,
      gilded: 0,
      archived: false,
      no_follow: true,
      author: 'Watchful1',
      num_comments: 1,
      edited: false,
      can_mod_post: false,
      created_utc: 1612384433.0,
      send_replies: true,
      parent_id: 't3_lbx5js',
      score: 1,
      author_fullname: 't2_d0z23',
      over_18: false,
      treatment_tags: [],
      approved_by: null,
      mod_note: null,
      all_awardings: [],
      subreddit_id: 't5_2qizd',
      body:
        "Have you tried logging in? [Here's the documentation](https://praw.readthedocs.io/en/latest/getting_started/authentication.html)",
      link_title:
        'Help with displaying post flair template [USER_REQUIRED error]',
      author_flair_css_class: 'lib-developer',
      name: 't1_glwllvw',
      author_patreon_flair: false,
      downs: 0,
      author_flair_richtext: [],
      is_submitter: false,
      body_html:
        '&lt;div class="md"&gt;&lt;p&gt;Have you tried logging in? &lt;a href="https://praw.readthedocs.io/en/latest/getting_started/authentication.html"&gt;Here&amp;#39;s the documentation&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;',
      gildings: {},
      collapsed_reason: null,
      distinguished: null,
      associated_award: null,
      stickied: false,
      author_premium: true,
      can_gild: true,
      top_awarded_type: null,
      author_flair_text_color: 'dark',
      score_hidden: false,
      permalink:
        '/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/glwllvw/',
      num_reports: null,
      link_permalink:
        'https://www.reddit.com/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/',
      report_reasons: null,
      link_author: 'Signal-Appointment-8',
      subreddit: 'redditdev',
      author_flair_text: 'RemindMeBot &amp; UpdateMeBot',
      link_url:
        'https://www.reddit.com/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/',
      created: 1612413233.0,
      collapsed: false,
      subreddit_name_prefixed: 'r/redditdev',
      controversiality: 0,
      locked: false,
      author_flair_background_color: null,
      collapsed_because_crowd_control: null,
      mod_reports: [],
      quarantine: false,
      subreddit_type: 'public',
      ups: 1,
    },
  },
];
