import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-comments',
  templateUrl: './comments.component.html',
  styleUrls: ['./comments.component.css'],
})
export class CommentsComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    console.log(this.comments);
    //this.data.data.children[1].data.body
  }

  data = {
    kind: 'Listing',
    data: {
      modhash: '',
      dist: 25,
      children: [
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbx5js',
            author_flair_template_id: '40bbb600-4ff1-11e7-bf1a-0e2aff1d0230',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glwllvw',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Watchful1',
            num_comments: 1,
            edited: false,
            can_mod_post: false,
            created_utc: 1612384433.0,
            send_replies: true,
            parent_id: 't3_lbx5js',
            score: 1,
            author_fullname: 't2_d0z23',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Have you tried logging in? [Here's the documentation](https://praw.readthedocs.io/en/latest/getting_started/authentication.html)",
            link_title:
              'Help with displaying post flair template [USER_REQUIRED error]',
            author_flair_css_class: 'lib-developer',
            name: 't1_glwllvw',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Have you tried logging in? &lt;a href="https://praw.readthedocs.io/en/latest/getting_started/authentication.html"&gt;Here&amp;#39;s the documentation&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/glwllvw/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/',
            report_reasons: null,
            link_author: 'Signal-Appointment-8',
            subreddit: 'redditdev',
            author_flair_text: 'RemindMeBot &amp; UpdateMeBot',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbx5js/help_with_displaying_post_flair_template_user/',
            created: 1612413233.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbvmfj',
            author_flair_template_id: '40bbb600-4ff1-11e7-bf1a-0e2aff1d0230',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glwb0uf',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Watchful1',
            num_comments: 1,
            edited: false,
            can_mod_post: false,
            created_utc: 1612380080.0,
            send_replies: true,
            parent_id: 't3_lbvmfj',
            score: 1,
            author_fullname: 't2_d0z23',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Change `praw.models.Redditor` to `reddit.Redditor` in both places.\n\nAlso you can't login with just client id and client secret, so you're operating in logged out mode here. Which is fine if you're doing that intentionally, but you won't be able to see anything that would require you to login to the account.",
            link_title: 'NotFound: received 404 HTTP response error help PRAW',
            author_flair_css_class: 'lib-developer',
            name: 't1_glwb0uf',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Change &lt;code&gt;praw.models.Redditor&lt;/code&gt; to &lt;code&gt;reddit.Redditor&lt;/code&gt; in both places.&lt;/p&gt;\n\n&lt;p&gt;Also you can&amp;#39;t login with just client id and client secret, so you&amp;#39;re operating in logged out mode here. Which is fine if you&amp;#39;re doing that intentionally, but you won&amp;#39;t be able to see anything that would require you to login to the account.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbvmfj/notfound_received_404_http_response_error_help/glwb0uf/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbvmfj/notfound_received_404_http_response_error_help/',
            report_reasons: null,
            link_author: 'EchelonInsights',
            subreddit: 'redditdev',
            author_flair_text: 'RemindMeBot &amp; UpdateMeBot',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbvmfj/notfound_received_404_http_response_error_help/',
            created: 1612408880.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glw7o1j',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Vault-TecTradingCo',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612378730.0,
            send_replies: true,
            parent_id: 't3_lbkdyj',
            score: 1,
            author_fullname: 't2_6ieue25a',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Well they already receive a message so I'd say it is unnecessary.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glw7o1j',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Well they already receive a message so I&amp;#39;d say it is unnecessary.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glw7o1j/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612407530.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glw2snn',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'mershed_perderders',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612376805.0,
            send_replies: true,
            parent_id: 't1_glvr2sl',
            score: 1,
            author_fullname: 't2_4zg39',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Functionally, not much.  There are a large number of such bots, and they are not *prima facie* against reddit's TOS.  It really is about implementation and what you want to do.  Is it a service, or just kinda spammy/karma-whoreish?\n\nSubreddit mods tend to take a dim view of such bots, and they do get banned from the top subreddits fairly quickly.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glw2snn',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Functionally, not much.  There are a large number of such bots, and they are not &lt;em&gt;prima facie&lt;/em&gt; against reddit&amp;#39;s TOS.  It really is about implementation and what you want to do.  Is it a service, or just kinda spammy/karma-whoreish?&lt;/p&gt;\n\n&lt;p&gt;Subreddit mods tend to take a dim view of such bots, and they do get banned from the top subreddits fairly quickly.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glw2snn/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612405605.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: '40bbb600-4ff1-11e7-bf1a-0e2aff1d0230',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glvzexx',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Watchful1',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612375490.0,
            send_replies: true,
            parent_id: 't1_gluktov',
            score: 1,
            author_fullname: 't2_d0z23',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Unfortunately the gilded listing only includes posts/comments that get silver/gold/platinum. It doesn't include items that only have any of the other awards.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: 'lib-developer',
            name: 't1_glvzexx',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Unfortunately the gilded listing only includes posts/comments that get silver/gold/platinum. It doesn&amp;#39;t include items that only have any of the other awards.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glvzexx/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: 'RemindMeBot &amp; UpdateMeBot',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612404290.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbn3mc',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glvuuy8',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: false,
            author: 'ItsTheRedditPolice',
            num_comments: 1,
            edited: false,
            can_mod_post: false,
            created_utc: 1612373723.0,
            send_replies: true,
            parent_id: 't3_lbn3mc',
            score: 4,
            author_fullname: 't2_2ofxixqd',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'you would basically change\n\n    skipped_sites = [google.com, reddit.com]\n    \n    if site in skipped_sites:\n        skip()\n    else:\n        doaction()\n\nto\n\n    whitelist_sites = [google.com, reddit.com]\n    \n    if site in whitelist_sites:\n        doaction()\n    else:\n        skip()\n\nthis is a very simple example, sorry if this comment isnt helpful much to you. you basically need to go through the code and find where it checks if the site should be skipped, and change it so it performs the action on the site instead of skipping. and will skip if the site is not in the list',
            link_title: 'Bot Help - Forked Python Script',
            author_flair_css_class: null,
            name: 't1_glvuuy8',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;you would basically change&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;skipped_sites = [google.com, reddit.com]\n\nif site in skipped_sites:\n    skip()\nelse:\n    doaction()\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;to&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;whitelist_sites = [google.com, reddit.com]\n\nif site in whitelist_sites:\n    doaction()\nelse:\n    skip()\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;this is a very simple example, sorry if this comment isnt helpful much to you. you basically need to go through the code and find where it checks if the site should be skipped, and change it so it performs the action on the site instead of skipping. and will skip if the site is not in the list&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbn3mc/bot_help_forked_python_script/glvuuy8/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbn3mc/bot_help_forked_python_script/',
            report_reasons: null,
            link_author: 'BloomerzUK',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbn3mc/bot_help_forked_python_script/',
            created: 1612402523.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 4,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glvr2sl',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'NewKidsOnAcid',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612372212.0,
            send_replies: true,
            parent_id: 't1_glvmyst',
            score: 1,
            author_fullname: 't2_7lwm9hw2',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "What's the difference between doing that and the distance conversion bot, for instance? That bot replies to such comments",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glvr2sl',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;What&amp;#39;s the difference between doing that and the distance conversion bot, for instance? That bot replies to such comments&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glvr2sl/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612401012.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbrkk5',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glvqfmb',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'John_Yuki',
            num_comments: 1,
            edited: false,
            can_mod_post: false,
            created_utc: 1612371957.0,
            send_replies: true,
            parent_id: 't3_lbrkk5',
            score: 1,
            author_fullname: 't2_omfbv',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "You're using `replace_more` incorrectly. You use it that method on it's own like so: \n\n\n    submission.comments.replace_more(limit=0)\n    for top_level_comment in submission.comments:\n        print(top_level_comment.body)\n\nAlso remember that `cuserid` will be a `Redditor` object, so you need to add in your `.name` after it too just like you did with `userid`",
            link_title:
              'How can I check if a comment has the same author as the post submitter?',
            author_flair_css_class: null,
            name: 't1_glvqfmb',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;You&amp;#39;re using &lt;code&gt;replace_more&lt;/code&gt; incorrectly. You use it that method on it&amp;#39;s own like so: &lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;submission.comments.replace_more(limit=0)\nfor top_level_comment in submission.comments:\n    print(top_level_comment.body)\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;Also remember that &lt;code&gt;cuserid&lt;/code&gt; will be a &lt;code&gt;Redditor&lt;/code&gt; object, so you need to add in your &lt;code&gt;.name&lt;/code&gt; after it too just like you did with &lt;code&gt;userid&lt;/code&gt;&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbrkk5/how_can_i_check_if_a_comment_has_the_same_author/glvqfmb/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbrkk5/how_can_i_check_if_a_comment_has_the_same_author/',
            report_reasons: null,
            link_author: 'cumwhisperer',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbrkk5/how_can_i_check_if_a_comment_has_the_same_author/',
            created: 1612400757.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glvmyst',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'ketralnis',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612370556.0,
            send_replies: true,
            parent_id: 't3_lbkdyj',
            score: 1,
            author_fullname: 't2_nn0q',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'Possible or no, auto replying to comments that didn\u2019t summon you will probably get your bot banned',
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glvmyst',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Possible or no, auto replying to comments that didn\u2019t summon you will probably get your bot banned&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glvmyst/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: 'reddit admin',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612399356.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: '',
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glumrgp',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'NewKidsOnAcid',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612352041.0,
            send_replies: true,
            parent_id: 't1_gluktov',
            score: 1,
            author_fullname: 't2_7lwm9hw2',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "No functionality. I just thought it would be hilarious to piggyback on everyone else's anonymous award spend.\n\nThen I realized it would also be good at harvesting karma. Therefore, I concluded, there's probably mechanisms in place to ban it.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glumrgp',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;No functionality. I just thought it would be hilarious to piggyback on everyone else&amp;#39;s anonymous award spend.&lt;/p&gt;\n\n&lt;p&gt;Then I realized it would also be good at harvesting karma. Therefore, I concluded, there&amp;#39;s probably mechanisms in place to ban it.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glumrgp/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612380841.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glukyvr',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'rtahkwa',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612350510.0,
            send_replies: true,
            parent_id: 't1_gluktov',
            score: 2,
            author_fullname: 't2_i0zcp',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body: "You're right, I forgot about that.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_glukyvr',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;You&amp;#39;re right, I forgot about that.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/glukyvr/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612379310.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 2,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gluktov',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: false,
            author: 'ThreshingBee',
            num_comments: 9,
            edited: 1612350571.0,
            can_mod_post: false,
            created_utc: 1612350389.0,
            send_replies: true,
            parent_id: 't1_gluin5e',
            score: 3,
            author_fullname: 't2_eqbbk',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "It should be possible to just track the sub's [gilded](https://www.reddit.com/r/redditdev/gilded/), instead of tracking everything.\n\nThere's not much activity here, but [another example](https://www.reddit.com/r/OldSchoolCool/gilded/).\n\nThough, this honestly sounds like a badbot to me. What is the functionality, OP?",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_gluktov',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;It should be possible to just track the sub&amp;#39;s &lt;a href="https://www.reddit.com/r/redditdev/gilded/"&gt;gilded&lt;/a&gt;, instead of tracking everything.&lt;/p&gt;\n\n&lt;p&gt;There&amp;#39;s not much activity here, but &lt;a href="https://www.reddit.com/r/OldSchoolCool/gilded/"&gt;another example&lt;/a&gt;.&lt;/p&gt;\n\n&lt;p&gt;Though, this honestly sounds like a badbot to me. What is the functionality, OP?&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/gluktov/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612379189.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 3,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbkdyj',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gluin5e',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'rtahkwa',
            num_comments: 9,
            edited: false,
            can_mod_post: false,
            created_utc: 1612348462.0,
            send_replies: true,
            parent_id: 't3_lbkdyj',
            score: 1,
            author_fullname: 't2_i0zcp',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Theoretically, yes.\nThe biggest caveat here is, that you can't search for every awarded post/comment. This means you'd have to check individual posts for awarded comments.",
            link_title: 'Bot that scans for awards',
            author_flair_css_class: null,
            name: 't1_gluin5e',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Theoretically, yes.\nThe biggest caveat here is, that you can&amp;#39;t search for every awarded post/comment. This means you&amp;#39;d have to check individual posts for awarded comments.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/gluin5e/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            report_reasons: null,
            link_author: 'NewKidsOnAcid',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbkdyj/bot_that_scans_for_awards/',
            created: 1612377262.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_l72570',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gltyp5w',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'ksush_12',
            num_comments: 4,
            edited: false,
            can_mod_post: false,
            created_utc: 1612331689.0,
            send_replies: true,
            parent_id: 't1_glk4tup',
            score: 1,
            author_fullname: 't2_nsw8d6n',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'Yes the user is added as a developer. Its still trowing error',
            link_title:
              'prawcore.exceptions.OAuthException: invalid_grant error processing request',
            author_flair_css_class: null,
            name: 't1_gltyp5w',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Yes the user is added as a developer. Its still trowing error&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/l72570/prawcoreexceptionsoauthexception_invalid_grant/gltyp5w/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/l72570/prawcoreexceptionsoauthexception_invalid_grant/',
            report_reasons: null,
            link_author: 'ksush_12',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/l72570/prawcoreexceptionsoauthexception_invalid_grant/',
            created: 1612360489.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbem7u',
            author_flair_template_id: '479b3c48-4ff1-11e7-9919-0e1edcbad3d2',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gltnri4',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'justcool393',
            num_comments: 4,
            edited: false,
            can_mod_post: false,
            created_utc: 1612325257.0,
            send_replies: true,
            parent_id: 't1_gltnlsm',
            score: 1,
            author_fullname: 't2_81vyw',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body: 'Of course, no problem! :)',
            link_title:
              'How do you check if a username is an approved user to give True or False?',
            author_flair_css_class: 'bot-developer',
            name: 't1_gltnri4',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Of course, no problem! :)&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/gltnri4/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            report_reasons: null,
            link_author: 'Caring_Cactus',
            subreddit: 'redditdev',
            author_flair_text: 'Totes/Snappy/BotTerminator/etc Dev',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            created: 1612354057.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbem7u',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gltnlsm',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Caring_Cactus',
            num_comments: 4,
            edited: false,
            can_mod_post: false,
            created_utc: 1612325174.0,
            send_replies: true,
            parent_id: 't1_gltlqcn',
            score: 1,
            author_fullname: 't2_6zbiazka',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "I got a weird error \"got an unexpected keyword argument 'user' when using [`user=submission.author.name`](https://user=submission.author.name) but using the predefined author I already had it worked!\n\nThank you :)",
            link_title:
              'How do you check if a username is an approved user to give True or False?',
            author_flair_css_class: null,
            name: 't1_gltnlsm',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;I got a weird error &amp;quot;got an unexpected keyword argument &amp;#39;user&amp;#39; when using &lt;a href="https://user=submission.author.name"&gt;&lt;code&gt;user=submission.author.name&lt;/code&gt;&lt;/a&gt; but using the predefined author I already had it worked!&lt;/p&gt;\n\n&lt;p&gt;Thank you :)&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/gltnlsm/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            report_reasons: null,
            link_author: 'Caring_Cactus',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            created: 1612353974.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbem7u',
            author_flair_template_id: '479b3c48-4ff1-11e7-9919-0e1edcbad3d2',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gltlqcn',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'justcool393',
            num_comments: 4,
            edited: false,
            can_mod_post: false,
            created_utc: 1612324192.0,
            send_replies: true,
            parent_id: 't3_lbem7u',
            score: 1,
            author_fullname: 't2_81vyw',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'Something like this\n\n    author = submission.author.name\n    listing = list(submission.subreddit.contributor(user=submission.author.name))\n    if listing:\n        print("yes, is an approved user")',
            link_title:
              'How do you check if a username is an approved user to give True or False?',
            author_flair_css_class: 'bot-developer',
            name: 't1_gltlqcn',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Something like this&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;author = submission.author.name\nlisting = list(submission.subreddit.contributor(user=submission.author.name))\nif listing:\n    print(&amp;quot;yes, is an approved user&amp;quot;)\n&lt;/code&gt;&lt;/pre&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/gltlqcn/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            report_reasons: null,
            link_author: 'Caring_Cactus',
            subreddit: 'redditdev',
            author_flair_text: 'Totes/Snappy/BotTerminator/etc Dev',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            created: 1612352992.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lbem7u',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gltkrw6',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Caring_Cactus',
            num_comments: 4,
            edited: false,
            can_mod_post: false,
            created_utc: 1612323702.0,
            send_replies: true,
            parent_id: 't3_lbem7u',
            score: 1,
            author_fullname: 't2_6zbiazka',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "I tried `if reddit.subreddit(mod_sub).contributor(author) == True:` but that's clearly wrong, I'm not sure what I'm doing.",
            link_title:
              'How do you check if a username is an approved user to give True or False?',
            author_flair_css_class: null,
            name: 't1_gltkrw6',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;I tried &lt;code&gt;if reddit.subreddit(mod_sub).contributor(author) == True:&lt;/code&gt; but that&amp;#39;s clearly wrong, I&amp;#39;m not sure what I&amp;#39;m doing.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/gltkrw6/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            report_reasons: null,
            link_author: 'Caring_Cactus',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lbem7u/how_do_you_check_if_a_username_is_an_approved/',
            created: 1612352502.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb8ppy',
            author_flair_template_id: '479b3c48-4ff1-11e7-9919-0e1edcbad3d2',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glt5y5w',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'justcool393',
            num_comments: 5,
            edited: 1612316975.0,
            can_mod_post: false,
            created_utc: 1612316405.0,
            send_replies: true,
            parent_id: 't1_glt5dp2',
            score: 1,
            author_fullname: 't2_81vyw',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Of course! :)\n\nAlso yeah, it is a shame it isn't documented.\n\nRemoving relationships (basically unbanning, unmuting, unwikibanning, demodding, etc) have no ratelimits whatsoever outside of the general ratelimits. Mutes have their own category. I don't remember what the mute limit it is off the top of my head, sorry about that\n\n&gt; I won't pry into how you know those are the values.\n\nExperimentation plus a read through of Reddit's code with regards to adding subreddit-to-user relationships",
            link_title: 'Understanding the rates and cooldowns in the API',
            author_flair_css_class: 'bot-developer',
            name: 't1_glt5y5w',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Of course! :)&lt;/p&gt;\n\n&lt;p&gt;Also yeah, it is a shame it isn&amp;#39;t documented.&lt;/p&gt;\n\n&lt;p&gt;Removing relationships (basically unbanning, unmuting, unwikibanning, demodding, etc) have no ratelimits whatsoever outside of the general ratelimits. Mutes have their own category. I don&amp;#39;t remember what the mute limit it is off the top of my head, sorry about that&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;I won&amp;#39;t pry into how you know those are the values.&lt;/p&gt;\n&lt;/blockquote&gt;\n\n&lt;p&gt;Experimentation plus a read through of Reddit&amp;#39;s code with regards to adding subreddit-to-user relationships&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/glt5y5w/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            report_reasons: null,
            link_author: 'Unbalanced_Life',
            subreddit: 'redditdev',
            author_flair_text: 'Totes/Snappy/BotTerminator/etc Dev',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            created: 1612345205.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb8ppy',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glt5dp2',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Unbalanced_Life',
            num_comments: 5,
            edited: false,
            can_mod_post: false,
            created_utc: 1612316130.0,
            send_replies: true,
            parent_id: 't1_glssk2v',
            score: 2,
            author_fullname: 't2_11k00q',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Ah yes, thank you kindly for that.\n\nShame it's not documented, but I won't pry into how you know those are the values. I'm going to assume mutes, un-mutes, and the like fall under the 1000 bans category.",
            link_title: 'Understanding the rates and cooldowns in the API',
            author_flair_css_class: null,
            name: 't1_glt5dp2',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Ah yes, thank you kindly for that.&lt;/p&gt;\n\n&lt;p&gt;Shame it&amp;#39;s not documented, but I won&amp;#39;t pry into how you know those are the values. I&amp;#39;m going to assume mutes, un-mutes, and the like fall under the 1000 bans category.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/glt5dp2/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            report_reasons: null,
            link_author: 'Unbalanced_Life',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            created: 1612344930.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 2,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb8ppy',
            author_flair_template_id: '479b3c48-4ff1-11e7-9919-0e1edcbad3d2',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glssk2v',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'justcool393',
            num_comments: 5,
            edited: false,
            can_mod_post: false,
            created_utc: 1612309951.0,
            send_replies: true,
            parent_id: 't3_lb8ppy',
            score: 1,
            author_fullname: 't2_81vyw',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "Hey there,\n\nIt's not documented but here is what I've written about the topic before\n\n&gt; The relationship limit is an \"abuse ratelimit\" that has an effect on adding bans, wiki bans, contributors, moderator invites, and mutes. The limit counts attempts to add, not just additions, so you should check to make sure that the user is a valid, existing person that's targetable before you attempt to add a relationship.\n&gt; \n&gt; The limits reset every 2 hours on the hour and is shared across an entire subreddit (the exception to this is the active moderator invite limit which can only be unratelimited by uninviting a moderator or having the user accept or decline an invite).\n&gt; \n&gt; The limits are currently as follows:\n&gt; \n&gt; * 1000 bans\n&gt; * 100 contributors\n&gt; * 100 moderator invites\n&gt;  * 15 active moderator invites\n&gt; \n&gt; You will not be ratelimited only in the following scenarios:\n&gt; \n&gt; 1. you are an admin in admin mode\n&gt; 2. you do not have the necessary permissions to add a relationship (e.g. access for bans, contributors, etc)\n&gt; 3. you are shadowbanned\n&gt; 4. you are suspended\n&gt; 5. quotas are disabled for your subreddit (this isn't something you can check and has to be manually changed by an admin)\n&gt; 6. there are too many active moderator invites and you are attempting to invite a moderator\n&gt; \n&gt; Even if you receive status 200, check the errors to make sure there isn't a `SUBREDDIT_RATELIMIT` error in there.",
            link_title: 'Understanding the rates and cooldowns in the API',
            author_flair_css_class: 'bot-developer',
            name: 't1_glssk2v',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Hey there,&lt;/p&gt;\n\n&lt;p&gt;It&amp;#39;s not documented but here is what I&amp;#39;ve written about the topic before&lt;/p&gt;\n\n&lt;blockquote&gt;\n&lt;p&gt;The relationship limit is an &amp;quot;abuse ratelimit&amp;quot; that has an effect on adding bans, wiki bans, contributors, moderator invites, and mutes. The limit counts attempts to add, not just additions, so you should check to make sure that the user is a valid, existing person that&amp;#39;s targetable before you attempt to add a relationship.&lt;/p&gt;\n\n&lt;p&gt;The limits reset every 2 hours on the hour and is shared across an entire subreddit (the exception to this is the active moderator invite limit which can only be unratelimited by uninviting a moderator or having the user accept or decline an invite).&lt;/p&gt;\n\n&lt;p&gt;The limits are currently as follows:&lt;/p&gt;\n\n&lt;ul&gt;\n&lt;li&gt;1000 bans&lt;/li&gt;\n&lt;li&gt;100 contributors&lt;/li&gt;\n&lt;li&gt;100 moderator invites\n\n&lt;ul&gt;\n&lt;li&gt;15 active moderator invites&lt;/li&gt;\n&lt;/ul&gt;&lt;/li&gt;\n&lt;/ul&gt;\n\n&lt;p&gt;You will not be ratelimited only in the following scenarios:&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;you are an admin in admin mode&lt;/li&gt;\n&lt;li&gt;you do not have the necessary permissions to add a relationship (e.g. access for bans, contributors, etc)&lt;/li&gt;\n&lt;li&gt;you are shadowbanned&lt;/li&gt;\n&lt;li&gt;you are suspended&lt;/li&gt;\n&lt;li&gt;quotas are disabled for your subreddit (this isn&amp;#39;t something you can check and has to be manually changed by an admin)&lt;/li&gt;\n&lt;li&gt;there are too many active moderator invites and you are attempting to invite a moderator&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Even if you receive status 200, check the errors to make sure there isn&amp;#39;t a &lt;code&gt;SUBREDDIT_RATELIMIT&lt;/code&gt; error in there.&lt;/p&gt;\n&lt;/blockquote&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/glssk2v/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            report_reasons: null,
            link_author: 'Unbalanced_Life',
            subreddit: 'redditdev',
            author_flair_text: 'Totes/Snappy/BotTerminator/etc Dev',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            created: 1612338751.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb8ppy',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glso17u',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Unbalanced_Life',
            num_comments: 5,
            edited: false,
            can_mod_post: false,
            created_utc: 1612307831.0,
            send_replies: true,
            parent_id: 't1_glslzn6',
            score: 1,
            author_fullname: 't2_11k00q',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'Your comment led me to realize I misinterpreted the meaning of GET on that page. Looks like that 100 refers to the size limit when retrieving a listing.',
            link_title: 'Understanding the rates and cooldowns in the API',
            author_flair_css_class: null,
            name: 't1_glso17u',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Your comment led me to realize I misinterpreted the meaning of GET on that page. Looks like that 100 refers to the size limit when retrieving a listing.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/glso17u/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            report_reasons: null,
            link_author: 'Unbalanced_Life',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            created: 1612336631.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb8ppy',
            author_flair_template_id: '40bbb600-4ff1-11e7-bf1a-0e2aff1d0230',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'glslzn6',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Watchful1',
            num_comments: 5,
            edited: 1612307971.0,
            can_mod_post: false,
            created_utc: 1612306896.0,
            send_replies: true,
            parent_id: 't3_lb8ppy',
            score: 1,
            author_fullname: 't2_d0z23',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "I think that's correct that there's a limit, and it's substantially lower than the other api actions limit, but I don't think it's documented anywhere. Where are you seeing 100?",
            link_title: 'Understanding the rates and cooldowns in the API',
            author_flair_css_class: 'lib-developer',
            name: 't1_glslzn6',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;I think that&amp;#39;s correct that there&amp;#39;s a limit, and it&amp;#39;s substantially lower than the other api actions limit, but I don&amp;#39;t think it&amp;#39;s documented anywhere. Where are you seeing 100?&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/glslzn6/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            report_reasons: null,
            link_author: 'Unbalanced_Life',
            subreddit: 'redditdev',
            author_flair_text: 'RemindMeBot &amp; UpdateMeBot',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb8ppy/understanding_the_rates_and_cooldowns_in_the_api/',
            created: 1612335696.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 1,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb5brq',
            author_flair_template_id: '479b3c48-4ff1-11e7-9919-0e1edcbad3d2',
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gls3wqt',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'justcool393',
            num_comments: 3,
            edited: false,
            can_mod_post: false,
            created_utc: 1612299515.0,
            send_replies: true,
            parent_id: 't1_gls3fpn',
            score: 3,
            author_fullname: 't2_81vyw',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              "If you're using a personal script (bots, etc), [see this tutorial](https://github.com/reddit-archive/reddit/wiki/OAuth2-Quick-Start-Example) or if you need no authentication, [see this page](https://github.com/reddit-archive/reddit/wiki/OAuth2#application-only-oauth).",
            link_title: 'Question about using API to get subreddit information',
            author_flair_css_class: 'bot-developer',
            name: 't1_gls3wqt',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: false,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;If you&amp;#39;re using a personal script (bots, etc), &lt;a href="https://github.com/reddit-archive/reddit/wiki/OAuth2-Quick-Start-Example"&gt;see this tutorial&lt;/a&gt; or if you need no authentication, &lt;a href="https://github.com/reddit-archive/reddit/wiki/OAuth2#application-only-oauth"&gt;see this page&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: true,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: 'dark',
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/gls3wqt/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/',
            report_reasons: null,
            link_author: 'Frigidissima',
            subreddit: 'redditdev',
            author_flair_text: 'Totes/Snappy/BotTerminator/etc Dev',
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/',
            created: 1612328315.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 3,
          },
        },
        {
          kind: 't1',
          data: {
            total_awards_received: 0,
            approved_at_utc: null,
            comment_type: null,
            awarders: [],
            mod_reason_by: null,
            banned_by: null,
            author_flair_type: 'text',
            removal_reason: null,
            link_id: 't3_lb5brq',
            author_flair_template_id: null,
            likes: null,
            replies: '',
            user_reports: [],
            saved: false,
            id: 'gls3fpn',
            banned_at_utc: null,
            mod_reason_title: null,
            gilded: 0,
            archived: false,
            no_follow: true,
            author: 'Frigidissima',
            num_comments: 3,
            edited: false,
            can_mod_post: false,
            created_utc: 1612299338.0,
            send_replies: true,
            parent_id: 't1_gls20yj',
            score: 2,
            author_fullname: 't2_4ccoinri',
            over_18: false,
            treatment_tags: [],
            approved_by: null,
            mod_note: null,
            all_awardings: [],
            subreddit_id: 't5_2qizd',
            body:
              'Thank you for that! My last question would be how would I go about putting the client ID into the link?',
            link_title: 'Question about using API to get subreddit information',
            author_flair_css_class: null,
            name: 't1_gls3fpn',
            author_patreon_flair: false,
            downs: 0,
            author_flair_richtext: [],
            is_submitter: true,
            body_html:
              '&lt;div class="md"&gt;&lt;p&gt;Thank you for that! My last question would be how would I go about putting the client ID into the link?&lt;/p&gt;\n&lt;/div&gt;',
            gildings: {},
            collapsed_reason: null,
            distinguished: null,
            associated_award: null,
            stickied: false,
            author_premium: false,
            can_gild: true,
            top_awarded_type: null,
            author_flair_text_color: null,
            score_hidden: false,
            permalink:
              '/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/gls3fpn/',
            num_reports: null,
            link_permalink:
              'https://www.reddit.com/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/',
            report_reasons: null,
            link_author: 'Frigidissima',
            subreddit: 'redditdev',
            author_flair_text: null,
            link_url:
              'https://www.reddit.com/r/redditdev/comments/lb5brq/question_about_using_api_to_get_subreddit/',
            created: 1612328138.0,
            collapsed: false,
            subreddit_name_prefixed: 'r/redditdev',
            controversiality: 0,
            locked: false,
            author_flair_background_color: null,
            collapsed_because_crowd_control: null,
            mod_reports: [],
            quarantine: false,
            subreddit_type: 'public',
            ups: 2,
          },
        },
      ],
      after: 't1_gls3fpn',
      before: null,
    },
  };

  comments = this.data.data.children;
}
